{{ config(
    pre_hook="ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = true",
    post_hook="GRANT SELECT ON TABLE {{ this }} TO ROLE TEST_DBT_ROLE"  
) }}

{{ config(
    tags=[var('TAG_FACT')]
) }}

WITH VOTES AS
(
SELECT ID
,NVL(ADB_ID,'N/A') AS ADB_ID
,NVL(ADB_SCORE,0) AS ADB_SCORE
,NVL(ADB_VOTES,0) AS ADB_VOTES
,NVL(ADB_POPULARITY,0) AS ADB_POPULARITY
,NVL(TADB_SCORE,0) AS ADB_SCORE
FROM
PROD.DBT_TRANSFORM.SCORES_VOTES_DIM
)

SELECT
TITLE
,TYPE
,DESCRIPTION
,FISCAL_YEAR
,VOTES.*
FROM PROD.DBT_TRANSFORM.SHOW_DETAILS_DIM DETAILS
LEFT JOIN
VOTES
ON
DETAILS.ID=VOTES.ID

