{{ config(
    pre_hook="ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = true",
    post_hook="GRANT SELECT ON TABLE {{ this }} TO ROLE TEST_DBT_ROLE"  
) }}

{{ config(
    tags=[var('TAG_FACT')]
) }}

WITH ACTORS AS
(
    SELECT 
    ID
    ,NAME
    FROM PROD.DBT_TRANSFORM.CREDITS_DIM
    WHERE ROLE='ARS'
)

SELECT
REPLACE(REPLACE(UPPER(CATEGORIES),'[',''),']','') AS CATEGORIES
,ARS.NAME
,SUM(CASE WHEN CATEGORIES IS NOT NULL THEN 1 ELSE 0 END) AS PERF_IND
FROM PROD.DBT_TRANSFORM.SHOW_DETAILS_DIM AS SD
LEFT JOIN
ARS
ON SD.ID=ARS.ID
WHERE NAME IS NOT NULL
GROUP BY 1,2


