{{ config(
    pre_hook="ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = true",
    post_hook="GRANT SELECT ON TABLE {{ this }} TO ROLE TEST_DBT_ROLE"  
) }}

{{ config(
    tags=[var('TAG_FACT')]
) }}

SELECT CATEGORIES,ROUND((TOTAL_MOS/TOTAL_CTT)*100) AS MOS_PERCENTAGE_SHARE
,ROUND((TOTAL_SWS/TOTAL_CTT)*100) AS SERIES_PERCENTAGE_SHARE FROM
(SELECT
REPLACE(REPLACE(UPPER(CATEGORIES),'[',''),']','') AS CATEGORIES
,TYPE
,SUM(CASE WHEN TTLE IS NOT NULL AND CATEGORIES IS NOT NULL AND TYPE='MI' 
    THEN 1 ELSE 0 END) AS TOTAL_MI
,SUM(CASE WHEN TTLE IS NOT NULL AND CATEGORIES IS NOT NULL AND TYPE='SW' 
    THEN 1 ELSE 0 END) AS TOTAL_SWS
,TOTAL_MI+TOTAL_SWS AS TOTAL_CTT    
FROM
PROD.DBT_TRANSFORM.SHOW_DETAILS_DIM
WHERE CATEGORIES IS NOT NULL AND TYPE IS NOT NULL
GROUP BY 1,2) SUBQ


